-- Drop all tables in correct order
DROP TABLE IF EXISTS migrations CASCADE;
DROP TABLE IF EXISTS vod_segments CASCADE;
DROP TABLE IF EXISTS vod_processing_history CASCADE;
DROP TABLE IF EXISTS vod_chapters CASCADE;
DROP TABLE IF EXISTS download_queue CASCADE;
DROP TABLE IF EXISTS vod_downloads CASCADE;
DROP TABLE IF EXISTS game_changes CASCADE;
DROP TABLE IF EXISTS vods CASCADE;
DROP TABLE IF EXISTS tracked_games CASCADE;
DROP TABLE IF EXISTS channels CASCADE;

-- Reset sequences
ALTER SEQUENCE IF EXISTS migrations_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS channels_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS tracked_games_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS vods_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS vod_chapters_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS vod_segments_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS vod_downloads_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS download_queue_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS vod_processing_history_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS game_changes_id_seq RESTART WITH 1;
